/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stm32f0xx.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

volatile uint32_t Tick = 0;
#define LED_TIME_SHORT (uint8_t)100
#define LED_TIME_LONG (uint16_t)1000
#define LED_TIME_BLINK (uint16_t)300
#define SAMPLE_TIME (uint8_t)40
#define DEBOUNCE_TIME (uint8_t)5

void blikac(void) // used to check if the time has already come for the led to change it's state
{
	static uint32_t delay;

	if (Tick > (delay + LED_TIME_BLINK))
	{
		GPIOA->ODR ^= (1 << 4);
		delay = Tick;
	}
}

void tlacitka(void) // creates 32 bit variable, shifts it every 5 ms left, when the button is not pressed, adds a '1' to it,
					// if the zeros move all the way to 0x7FFF, trigger the led
{
	static uint32_t off_time;
	static uint32_t stop_sample = 0;
	static uint16_t debounce_s1 = 0xFFFF;
	static uint16_t debounce_s2 = 0xFFFF;

	if(Tick > stop_sample)
	{
		debounce_s1 = debounce_s1 << 1;
		if(GPIOC->IDR & (1 << 1)) debounce_s1 |= 0x0001;

		debounce_s2 = debounce_s2 << 1;
		if(GPIOC->IDR & (1 << 0)) debounce_s2 |= 0x0001;
		stop_sample = Tick + DEBOUNCE_TIME;
	}


	if ((debounce_s2 == 0x8000))
	{ // falling edge
		off_time= Tick + LED_TIME_SHORT;
		GPIOB->BSRR = (1 << 0);
		debounce_s2 = 0xFFFF;
	}

	if ((debounce_s1 == 0x8000))
	{ // falling edge
		off_time = Tick + LED_TIME_LONG;
		GPIOB->BSRR = (1 << 0);
		debounce_s1 = 0xFFFF;
	}

	if (Tick > off_time)
	{
		GPIOB->BRR = (1 << 0);
	}

}
/*void tlacitka(void) // checks whether a button is pressed or not every 40 ms
{
	static uint32_t old_s2;
	static uint32_t off_time;
	static uint32_t old_s1;
	static uint32_t stop_sample;
	uint32_t new_s2;
	uint32_t new_s1;


	if(Tick > stop_sample)
	{
		new_s2 = GPIOC->IDR & (1 << 0);
		new_s1 = GPIOC->IDR & (1 << 1);
		stop_sample = Tick + SAMPLE_TIME;
	}


	if (old_s2 && !new_s2)
	{ // falling edge
		off_time= Tick + LED_TIME_SHORT;
		GPIOB->BSRR = (1 << 0);
	}
	old_s2 = new_s2;

	if (old_s1 && !new_s1)
	{ // falling edge
		off_time = Tick + LED_TIME_LONG;
		GPIOB->BSRR = (1 << 0);
	}
	old_s1 = new_s1;

	if (Tick > off_time)
	{
		GPIOB->BRR = (1 << 0);
	}

}*/

int main(void)
{
	SysTick_Config(8000); // 1ms

	RCC->AHBENR |= RCC_AHBENR_GPIOAEN | RCC_AHBENR_GPIOBEN | RCC_AHBENR_GPIOCEN; // enable
	GPIOA->MODER |= GPIO_MODER_MODER4_0; // LED1 = PA4, output
	GPIOB->MODER |= GPIO_MODER_MODER0_0; // LED2 = PB0, output
	GPIOC->PUPDR |= GPIO_PUPDR_PUPDR0_0; // S2 = PC0, pullup
	GPIOC->PUPDR |= GPIO_PUPDR_PUPDR1_0; // S1 = PC1, pullup

	RCC->APB2ENR |= RCC_APB2ENR_SYSCFGEN;

	/*SYSCFG->EXTICR[0] |= SYSCFG_EXTICR1_EXTI0_PC; // select PC0 for EXTI0
	EXTI->IMR |= EXTI_IMR_MR0; // mask
	EXTI->FTSR |= EXTI_FTSR_TR0; // trigger on falling edge
	NVIC_EnableIRQ(EXTI0_1_IRQn); // enable EXTI0_1*/


	for(;;)
	{
		blikac();
		tlacitka();
	}
}

/*void EXTI0_1_IRQHandler(void)
{
	if (EXTI->PR & EXTI_PR_PR0) { // check line 0 has triggered the IT
		EXTI->PR |= EXTI_PR_PR0; // clear the pending bit
		GPIOB->ODR ^= (1 << 0); // toggle - reads ODR register's value then xors it with the right side
	}
}*/

void SysTick_Handler(void) // code that executes once the system counter increments
{
	Tick++;
}



/*int main(void)
{
	RCC->AHBENR |= RCC_AHBENR_GPIOAEN; //cpu clock setup
	GPIOA->MODER |= GPIO_MODER_MODER5_0; //set LED pin as output

	uint8_t pole[32] = {1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1,
			1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0 , 0, 0, 0, 0, 0, 0};

	uint32_t morse_code = 0b10101001110111011100101010000000;

     Loop forever
	for(;;)
	{

		for(uint8_t i = 0; i < sizeof(pole) / sizeof(pole[0]); i++)
		{
			if(pole[i]) GPIOA->BSRR = (1 << 5);
			else GPIOA->BRR = (1 << 5);

			for (volatile uint32_t i = 0; i < 100000; i++) {};
			// GPIOA->BSRR = (1 << 5)  //set
			// for (volatile uint32_t i = 0; i < 100000; i++) {};
			// GPIOA->BRR = (1 << 5);  //reset
			// for (volatile uint32_t i = 0; i < 100000; i++) {};
		}
		for(uint8_t i = 0; i < (8 * sizeof(morse_code)); i++)
		{
			if(morse_code & ((uint32_t)1) << ((8 * sizeof(morse_code) - 1 - i))) GPIOA->BSRR = (1 << 5);
			else GPIOA->BRR = (1 << 5);

			for (volatile uint32_t i = 0; i < 100000; i++) {}; //delay
		}

	}
}*/
